### ISSUE TITLE
Create SolarEdge integration

### ISSUE THREAD

**Issue by pkuehnel** [pkuehnel/SmartTeslaAmpSetter#128]
[API Documentation](https://www.solaredge.com/sites/default/files/se_monitoring_api.pdf) page 25. Sample response: page 26.

**Comment by pkuehnel** [comment]
Important: Max 300 requests per day. Number of requests based on sunrise and sunset of location and if car requests charging.

**Comment by pkuehnel** [comment]
Steht zum Test bereit unter `:solaredge` statt `:latest` auch smartteslaampsetter auf das `solaredge` Tag umbauen.
Sollte dann so ausschauen, CloudUrl muss halt angepasst werden.
```
services:
    solaredgeplugin:
    image: pkuehnel/smartteslaampsettersolaredgeplugin:solaredge
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:8453
      - CloudUrl=https://monitoringapi.solaredge.com/site/1561056/currentPowerFlow.json?api_key=asdfasdfasdfasdfasdfasdf&
      - RefreshIntervallSeconds=360
     ports:
      - 8453:8453
```

Beim Smartteslaampsetter dann wie gesagt ebenfalls `:solaredge` als Tag und folgende Environmentvariablen:
```
- CurrentPowerToGridUrl=http://solaredgeplugin:8453/api/CurrentValues/GetPowerToGrid
- CurrentInverterPowerUrl=http://solaredgeplugin:8453/api/CurrentValues/GetInverterPower
```
